apiVersion: v1
kind: Service
metadata:
  name: aksflow
  namespace: namespace-workflow-1685724825972
spec:
  type: LoadBalancer
  selector:
    app: aksflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80